import 'package:dotnetapiflutter/api_hendler.dart';
import 'package:dotnetapiflutter/modle.dart';
import 'package:flutter/material.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';
import 'package:form_builder_validators/form_builder_validators.dart';
import 'package:http/http.dart' as http;

class CreateUserPage extends StatefulWidget {
  @override
  State<CreateUserPage> createState() => _CreateUserPageState();
}

class _CreateUserPageState extends State<CreateUserPage> {
  final _formKey = GlobalKey<FormBuilderState>();

  final api_hendler apiHandler = api_hendler();

  void createUser() async {
    if (_formKey.currentState!.saveAndValidate()) {
      final data = _formKey.currentState!.value;

      final newUser = User(
        userId: 0, // Assuming userId is generated by the server
        name: data['name'],
        address: data['address'],
      );

      await apiHandler.postUser(user: newUser);
    }

    if (!mounted) return;

    Navigator.pop(context);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Create User"),
        centerTitle: true,
        backgroundColor: Colors.black,
        foregroundColor: Colors.yellowAccent,
      ),
      body: Padding(
        padding: const EdgeInsets.all(10),
        child: FormBuilder(
          key: _formKey,
          child: Column(
            children: [
              FormBuilderTextField(
                name: 'name',
                validator: FormBuilderValidators.compose(
                  [FormBuilderValidators.required()],
                ),
                decoration: InputDecoration(labelText: 'Enter your name'),
              ),
              SizedBox(height: 20),
              FormBuilderTextField(
                name: 'address',
                validator: FormBuilderValidators.compose(
                  [FormBuilderValidators.required()],
                ),
                decoration: InputDecoration(labelText: 'Enter your address'),
              ),
              SizedBox(height: 20),
              ElevatedButton(
                onPressed: createUser,
                child: Text('Create User'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
